### ISSUE TITLE
Is it possible to integrate with choosewin.vim?

### ISSUE THREAD

**Issue by p0deje** [yssl/QFEnter#19]
Hello and thank you for this terrific plugin!

I wonder if it's possible to somehow integrate QFEnter with [choosewin.vim](https://github.com/t9md/vim-choosewin). This plugin prompts to select a particular window to be chosen when opening a file. An example of such integration is [nerdtree_choosewin-plugin](https://github.com/weilbith/nerdtree_choosewin-plugin), so I wonder if QFEnter can allow something similar either built-in or by providing some API that can be used for integration.

**Comment by yssl** [comment]
That's a good idea :)

After a quick look at the code of choosewin.vim, nerdtree_choosewin-plugin, and this QFEnter, I found that additional cmds - custom_open, custom_cnext, custom_cprev, custom_open_keep, custom, custom_cnext_keep, custom_cprev_keep - and global variable such as g:qfenter_customwin_handler might be a solution.

But actually it requires too many new cmds. So I'm considering providing an additional way of specifying cmd-keymap pairs similar to NERDTreeAddKeyMap(), for this kind of "custom" handling cases, instead of providing all those new cmds.
For example, 
```
QFEnterAddKeyMap({
      \ 'wintype': 'ChooseWinOpen',
      \ 'opencmd':    'cc',
      \ 'keepfocus': 0,
\ })
```

What do you think?

**Comment by p0deje** [comment]
Sounds great, though I'm not 100% sure how to set things up :)

**Comment by yssl** [comment]
I've uploaded the version 2.4.0 that supports the use of custom functions to specify a target window.
You can refer https://github.com/yssl/QFEnter#use-of-custom-functions-to-specify-a-target-window-for-advanced-users.
Sorry for the late update.
