### ISSUE TITLE
QFEnter raises error when using quickfix list with vim-bookmarks plugin

### ISSUE THREAD

**Issue by fwy** [yssl/QFEnter#27]
I use both the QFEnter and vim-bookmarks plugin, and am receiving a QFEnter error in some cases.  I realize this is not the place to post vim-bookmarks issues, but my first impression is that this is a problem that should be fixed in QFEnter.  I am using QFEnter with all default settings.

The vim-bookmarks plugin displays predefined bookmarks inside the quickfix window.  If I configure the quickfix window to auto-close when a bookmark is selected from there (this is a vim-bookmarks setting), I receive this error.

```
Error detected while processing function QFEnter#OpenQFItem[8]..<SNR>116_OpenQFItem[37]..<SNR>116_JumpToWin:
Line    1:
E16: Invalid range: 2wincmd w
```

After pressing Enter to move past the error, focus jumps correctly to the selected bookmark in the previously focused window, which is what I want.  The error occurs in both vim and neovim.

The error does not occur If I happen to have another window open (without focus) at the time the quickfix list is being used.

After reviewing the QFEnter code and a few web searches, I found that modifying the QFEnter JumpToWin function as follows fixes the problem.

```
fun! s:JumpToWin(winnum)
	silent! exec a:winnum.'wincmd w'
endfun
```

Because the error is not fatal, using 'silent!' to ignore it gives the desired behavior.  I don't know if this fix has any unwanted side effects and therefore didn't create a PR for it, but it looks reasonable to me.  I could imagine this becoming a nuisance error with other plugins as well.

What do you think?

**Comment by yssl** [comment]
Sorry for the very late reply.

If `g:bookmark_auto_close` is used in vim-bookmarks, the quickfix window is closed by WinLeave autocmd event:
https://github.com/MattesGroeger/vim-bookmarks/blob/33743fc73257d0a14c5f0c560a595cd7df8e1fe9/plugin/bookmark.vim#L200
https://github.com/MattesGroeger/vim-bookmarks/blob/33743fc73257d0a14c5f0c560a595cd7df8e1fe9/plugin/bookmark.vim#L506

In QFEnter, if the default `g:qfenter_prevtabwin_policy` setting ('qf') is used, the focus jumps to the target window first:
https://github.com/yssl/QFEnter/blob/master/autoload/QFEnter.vim#L121
and returns to the quickfix:
https://github.com/yssl/QFEnter/blob/master/autoload/QFEnter.vim#L130
https://github.com/yssl/QFEnter/blob/master/autoload/QFEnter.vim#L136
(and again jumps to the target window to open the item in it.)

In your setting, the quickfix window is closed due to the WinLeave event when jumping to the target window, so returning to the quickfix will report a `E16: Invalid range` error.

After a bit of googling, I found some bug reports about the similar situation (ex. https://groups.google.com/g/vim_dev/c/KE3h0THwizc) and found that this error occurs after Patch [v7.4.565](https://github.com/vim/vim/releases/tag/v7.4.565) of Vim.
Before Jan 07, 2015, QFEnter would have ignored this invalid winnr error in this situation, like the 'silent!' solution you suggested.
So, I think your suggestion is reasonable.

Could you create a PR for it?

**Comment by yssl** [comment]
Updated in the latest code.
