### ISSUE TITLE
QFEnter creates new buffers named: ""[No Name]"

### ISSUE THREAD

**Issue by RobertBuhren** [yssl/QFEnter#8]
When using e.g. <leader><Enter> to open an entry in a vertical split, a new buffer is also created with the name ""[No Name]"".  

This is kinda annoying because after using QFEnter several times you'll end up with several useless buffers.

Regards,

Robert

**Comment by yssl** [comment]
Really? How can I check? I couldn't find any [No Name] buffers from the :buffers command.
Please let me know how to reproduce it.

**Comment by RobertBuhren** [comment]
Here's a test case that will produce an extra "[No Name]" buffer:

    vim test.c
    :grep! -Ir test .
    :copen
    <leader>Enter
    :buffers

When I use a plain "Enter" to open an Item in the quickfix window, no extra buffer is created.
When I instead use <leader>Enter to open the Item in a vertical split, the Item is opened in a new window AND an extra buffer is created with the name "[No Name]". 

I hope you can reproduce the error.

Regards,

Robert

**Comment by RobertBuhren** [comment]
Oooops, I didn'nt intend to close the issue....

**Comment by yssl** [comment]
It's strange.. I cannot reproduce it also with your guide. In my case, "No Name" buffer is created after :vnew, then it is changed to a file's buffer after :cc. So finally the useless "No Name" buffer does not exist in the result of :buffers.

**Comment by kminh** [comment]
@RobertBuhren what version of Vim are you using?

This issue is not related to QFEnter I believe, as you can reproduce that with a vanilla Vim installation (use Ctrl-W Enter). 

A "No Name" buffer is also created when you open an item in the quickfix list in a new tab. Again, QFEnter is not needed to reproduce, just set `switchbuf+=newtab` in your vimrc and try to open an item in the quickfix list that has not been opened before.

This is a really annoying bug though.

**Comment by kuzyo** [comment]
Have the same issue. After leader + Enter have New buffer, that also appears in :ls.

**Comment by yssl** [comment]
Sorry for late reply.
kminh, thank you for the comment. But unfortunately, I still could not see "No Name" buffer with disabling QFEnter and setting switchbuf+=newtab.
I'm currently working on Windows 10 with gvim 7.4, but still can not find "No Name" buffer in the result of :ls or :buffers after <Leader>Enter.
The reason is so unclear and even I could not reproduce it, so it's very hard to look into it.
Anybody having any idea about the problem?
